[build]
  base = "cyber_repo"
  publish = "cyber_repo/public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.139.4"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
